In [1]:
import numpy as np

In [2]:
A1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
A1=A1.reshape(3,3)
A1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
A2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
A2[A2%2!=0]=-1
A2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [4]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(np.where(x>y))
print(np.where(x==y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [5]:
A4=np.arange(100).reshape(5,-1)
A4[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [6]:
np.random.randint(30, 41, 10)

array([32, 33, 36, 37, 35, 37, 40, 35, 30, 37])

In [7]:
A = ((1, 2, 3), (4, 5, 6), (7, 8, 10))
B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3))
A=np.array(A)
B=np.array(B)
C=A+B
E=A-B
print(C,"\n")
print(E,"\n")

print(np.sum(A),"\n")
print(np.sum(B,axis=0),"\n")
print(np.sum(C,axis=1),"\n")

D=np.dot(A,B)
print(D,"\n")

E=np.sort(C,axis=None).reshape((3,3))
print(E,"\n")

print(E.T)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]] 

[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]] 

46 

[12 15 19] 

[31 30 31] 

[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]] 

[[ 8  8  8]
 [10 10 10]
 [12 13 13]] 

[[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]
